- name: Set up SLURM on compute nodes
  hosts: compute_nodes
  become: yes

  roles:
    - prereqs
    - { role: munge, tasks_from: install_munge.yml }
    - { role: munge, tasks_from: start_munge.yml }
    - { role: munge, tasks_from: copy_munge_key.yml }
    - { role: munge, tasks_from: test_munge.yml }
    - { role: slurm, tasks_from: install_slurm.yml }
