- name: Create SLURM database and user
  shell: |
    mysql -u root -p'{{ mysql_root_password }}' <<EOF
    CREATE DATABASE slurm_acct_db;
    SET PASSWORD FOR 'slurm'@'localhost' = PASSWORD('slurmdbpass');
    GRANT USAGE ON *.* TO 'slurm'@'localhost';
    GRANT ALL PRIVILEGES ON slurm_acct_db.* TO 'slurm'@'localhost';
    FLUSH PRIVILEGES;
    EOF
  args:
    executable: /bin/bash
